"""empty message

Revision ID: 2d0f903b0db8
Revises: b9a30538f583
Create Date: 2024-05-17 15:48:49.576913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0f903b0db8'
down_revision = 'b9a30538f583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('employee',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Position', sa.String(length=150), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Address', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Photo', sa.String(length=200), nullable=True),
    sa.Column('Parent1', sa.String(length=100), nullable=False),
    sa.Column('Parent2', sa.String(length=100), nullable=True),
    sa.Column('Phone1', sa.String(length=100), nullable=True),
    sa.Column('Phone2', sa.String(length=100), nullable=True),
    sa.Column('Email1', sa.String(length=100), nullable=True),
    sa.Column('Email2', sa.String(length=100), nullable=True),
    sa.Column('Address1', sa.String(length=100), nullable=True),
    sa.Column('Address2', sa.String(length=100), nullable=True),
    sa.Column('City_ST_Zip1', sa.String(length=100), nullable=True),
    sa.Column('City_ST_Zip2', sa.String(length=100), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('employee')
    op.drop_table('user')
    # ### end Alembic commands ###
