"""empty message

Revision ID: 93bf6e7db872
Revises: 2d0f903b0db8
Create Date: 2024-07-03 12:51:44.489441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bf6e7db872'
down_revision = '2d0f903b0db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('City_ST_Zip2')
        batch_op.drop_column('City_ST_Zip1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('City_ST_Zip1', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('City_ST_Zip2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
